steps:
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d']
  - name: 'docker'
    args: ['tag', 'rancid-tomatillos_web:latest', 'gcr.io/robust-service-318217/rancid-tomatillos-web/$COMMIT_SHA']
  - name: 'docker'
    args: ['tag', 'rancid-tomatillos_api:latest', 'gcr.io/robust-service-318217/rancid-tomatillos-api/$COMMIT_SHA']
images:
  - 'gcr.io/robust-service-318217/rancid-tomatillos-web/$COMMIT_SHA'
  - 'gcr.io/robust-service-318217/rancid-tomatillos-api/$COMMIT_SHA'
options:
  env:
    - 'TMDB_TOKEN=${_TMDB_TOKEN}'
    - 'MONGO_ATLAS_USERNAME=${_MONGO_ATLAS_USERNAME}'
    - 'MONGO_ATLAS_PASSWORD=${_MONGO_ATLAS_PASSWORD}'
    - 'MONGO_ATLAS_DATABASE=${_MONGO_ATLAS_DATABASE}'
    - 'MONGO_ATLAS_CLUSTER=${_MONGO_ATLAS_CLUSTER}'
