steps:
  - name: 'docker/compose:1.29.2'
    args: ['up', '-d', '--build']
  - name: 'docker'
    args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA'
options:
  env:
    - 'TMDB_TOKEN=${_TMDB_TOKEN}'
    - 'MONGO_ATLAS_USERNAME=${_MONGO_ATLAS_USERNAME}'
    - 'MONGO_ATLAS_PASSWORD=${_MONGO_ATLAS_PASSWORD}'
    - 'MONGO_ATLAS_DATABASE=${_MONGO_ATLAS_DATABASE}'
    - 'MONGO_ATLAS_CLUSTER=${_MONGO_ATLAS_CLUSTER}'
