steps:
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rt_api', './api']
  - name: 'docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rt_api']
  - name: 'docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/rt_web', './web']
  - name: 'docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rt_web']
options:
  env:
    - 'TMDB_TOKEN=${_TMDB_TOKEN}'
    - 'MONGO_ATLAS_USERNAME=${_MONGO_ATLAS_USERNAME}'
    - 'MONGO_ATLAS_PASSWORD=${_MONGO_ATLAS_PASSWORD}'
    - 'MONGO_ATLAS_DATABASE=${_MONGO_ATLAS_DATABASE}'
    - 'MONGO_ATLAS_CLUSTER=${_MONGO_ATLAS_CLUSTER}'
