steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    for dir in */; do
      config="${dir}cloudbuild.yaml"
      if [[ ! -f "${config}" ]]; then
        continue
      fi

      echo "Building $d ... "
      (
        gcloud builds submit $d --config=${config}
      ) &
    done
    wait
options:
  env:
    - 'TMDB_TOKEN=${_TMDB_TOKEN}'
    - 'MONGO_ATLAS_USERNAME=${_MONGO_ATLAS_USERNAME}'
    - 'MONGO_ATLAS_PASSWORD=${_MONGO_ATLAS_PASSWORD}'
    - 'MONGO_ATLAS_DATABASE=${_MONGO_ATLAS_DATABASE}'
    - 'MONGO_ATLAS_CLUSTER=${_MONGO_ATLAS_CLUSTER}'
