version: "3.9"
services:
  web:
    container_name: web
    build: ./web
    ports:
      - 8080:8080
    env_file:
      - ./web/.env.local
    restart: always
    links:
      - api
    networks:
      - yearone_network
  api:
    container_name: api
    build: ./api
    ports:
      - 8081:8081
    environment:
      MONGO_USERNAME: "${MONGO_ATLAS_USERNAME}"
      MONGO_PASSWORD: "${MONGO_ATLAS_PASSWORD}"
      MONGO_DATABASE: "${MONGO_ATLAS_DATABASE}"
      MONGO_CLUSTER: "${MONGO_ATLAS_CLUSTER}"
    restart: always
    networks:
      - yearone_network
networks:
  yearone_network:
    driver: bridge
