version: "3.9"
services:
  web:
    container_name: web_dev
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      TMDB_TOKEN: "${TMDB_TOKEN}"
      NEXT_PUBLIC_ROOT_URL: "${ROOT_URL}"
      NEXT_PUBLIC_API_URL: "${API_URL}"
    restart: on-failure
    links:
      - api
  api:
    container_name: api_dev
    build: 
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./api:/usr/local/go/src/app
    environment:
      MONGO_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DATABASE: "${MONGO_INITDB_ROOT_DATABASE}"
      MONGO_CLUSTER: "${MONGO_CLUSTER}"
    restart: always
    links:
      - mongodb
  mongodb:
    container_name: mongodb_dev
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_ROOT_DATABASE: "${MONGO_INITDB_ROOT_DATABASE}"
volumes:
  mongo:
