version: "3.9"
services:
  web:
    container_name: web_dev
    build:
      context: ./web
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    environment:
      TMDB_TOKEN: "${TMDB_TOKEN}"
    restart: on-failure
    links:
      - api
    networks:
      - yearone_dev_network
  api:
    container_name: api_dev
    build: 
      context: ./api
      dockerfile: dev.Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./api:/usr/local/go/src/app
    environment:
      MONGO_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_DATABASE: "${MONGO_INITDB_ROOT_DATABASE}"
      MONGO_CLUSTER: "${MONGO_CLUSTER}"
    restart: always
    links:
      - mongodb
    networks:
      - yearone_dev_network
  mongodb:
    container_name: mongodb_dev
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_INITDB_ROOT_PASSWORD}"
      MONGO_INITDB_ROOT_DATABASE: "${MONGO_INITDB_ROOT_DATABASE}"
    networks:
      - yearone_dev_network
volumes:
  mongo:
networks:
  yearone_dev_network:
    driver: bridge
